<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Hermodr.Publisher.AuditTrail\Hermodr.Publisher.AuditTrail.csproj" />
    <ProjectReference Include="..\..\src\Hermodr.AuditTrail.InMemory\Hermodr.AuditTrail.InMemory.csproj" />
    <ProjectReference Include="..\..\src\Hermodr.TestPublisher\Hermodr.TestPublisher.csproj" />
  </ItemGroup>

</Project>
