<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Title>Hermodr Dapr Publisher</Title>
    <Description>Provides a publisher of events through the Dapr pub/sub building block</Description>
    <PackageTags>event;events;ddd;publisher;dapr;messaging;pubsub</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CloudNative.CloudEvents.SystemTextJson" Version="2.9.0" />
    <PackageReference Include="Dapr.Client" Version="1.18.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Hermodr.Publisher\Hermodr.Publisher.csproj" />
  </ItemGroup>
</Project>