name: Build and Test

on:
  workflow_call:
    inputs:
      collect-coverage:
        description: 'Whether to collect and upload code coverage reports to Codecov'
        type: boolean
        default: false
      restrict-build-to-tfm:
        description: 'Whether to restrict the build step to the matrix target framework (useful for PR builds)'
        type: boolean
        default: false

jobs:
  build:
    name: Build & Test (.NET ${{ matrix.dotnet-version }} - ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet-version: ['8.0.x', '9.0.x', '10.0.x']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Derive Target Framework (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          VERSION=$(echo "${{ matrix.dotnet-version }}" | sed 's/[^0-9.]*//g')
          VERSION=$(echo "${VERSION}" | sed 's/\.$//')
          echo "DOTNET_TFM=net${VERSION}" >> $GITHUB_ENV

      - name: Derive Target Framework (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: |
          $VERSION = "${{ matrix.dotnet-version }}".Substring(0, "${{ matrix.dotnet-version }}".LastIndexOf('.'))
          "DOTNET_TFM=net$VERSION" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v5
        with: dotnet-version: 3.1.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build (framework-restricted)
        if: inputs.restrict-build-to-tfm
        run: dotnet build -c Release --no-restore --framework ${{ env.DOTNET_TFM }}

      - name: Build
        if: ${{ !inputs.restrict-build-to-tfm }}
        run: dotnet build -c Release --no-restore

      - name: Test (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: >
          dotnet test -c Release --no-build --verbosity normal
          --framework ${{ env.DOTNET_TFM }}
          ${{ inputs.collect-coverage && '-- --coverage --coverage-output-format cobertura' || '' }}

      - name: Test (Windows)
        if: startsWith(matrix.os, 'windows')
        run: >
          dotnet test -c Release --no-build --verbosity normal
          --framework ${{ env.DOTNET_TFM }}
          -- --filter-not-trait "DisableCICD=Windows"
          ${{ inputs.collect-coverage && '--coverage --coverage-output-format cobertura' || '' }}

      - name: Upload coverage to Codecov
        if: inputs.collect-coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./**/*.cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}



