name: Events CI/CD

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/build-test.yml
    with:
      collect-coverage: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish:
    name: Publish Packages
    needs: build
    uses: ./.github/workflows/publish-packages.yml
    with:
      push-to-nuget-org: false
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  clean:
    name: Clean Old Packages
    needs: publish
    uses: ./.github/workflows/clean-packages.yml