name: Clean Events Packages

on:
  workflow_call:

permissions:
  packages: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Clean Deveel.Events.Annotations package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Deveel.Events.Annotations'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Deveel.Events.Amqp.Annotations package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Deveel.Events.Amqp.Annotations'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Deveel.Events.Schema package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Deveel.Events.Schema'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Deveel.Events.Schema.AsyncApi package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Deveel.Events.Schema.AsyncApi'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Deveel.Events.Schema.Yaml package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Deveel.Events.Schema.Yaml'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Deveel.Events.Publisher package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Deveel.Events.Publisher'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Deveel.Events.Publisher.AzureServiceBus package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Deveel.Events.Publisher.AzureServiceBus'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Deveel.Events.Publisher.MassTransit package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Deveel.Events.Publisher.MassTransit'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Deveel.Events.Publisher.RabbitMq package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Deveel.Events.Publisher.RabbitMq'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Deveel.Events.Publisher.Webhook package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Deveel.Events.Publisher.Webhook'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Deveel.Events.Publisher.Outbox package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Deveel.Events.Publisher.Outbox'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Deveel.Events.Publisher.Outbox.EntityFramework package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Deveel.Events.Publisher.Outbox.EntityFramework'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Deveel.Events.Subscriptions package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Deveel.Events.Subscriptions'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Deveel.Events.TestPublisher package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Deveel.Events.TestPublisher'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true