name: Clean Events Packages

on:
  workflow_call:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Clean Hermodr.Annotations package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Hermodr.Annotations'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Hermodr.Amqp.Annotations package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Hermodr.Amqp.Annotations'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Hermodr.Schema package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Hermodr.Schema'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Hermodr.Schema.AsyncApi package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Hermodr.Schema.AsyncApi'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Hermodr.Schema.Yaml package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Hermodr.Schema.Yaml'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Hermodr.Publisher package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Hermodr.Publisher'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Hermodr.Publisher.AzureServiceBus package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Hermodr.Publisher.AzureServiceBus'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Hermodr.Publisher.MassTransit package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Hermodr.Publisher.MassTransit'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Hermodr.Publisher.RabbitMq package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Hermodr.Publisher.RabbitMq'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Hermodr.Publisher.Webhook package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Hermodr.Publisher.Webhook'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Hermodr.Publisher.Outbox package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Hermodr.Publisher.Outbox'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Hermodr.Publisher.Outbox.EntityFramework package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Hermodr.Publisher.Outbox.EntityFramework'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Hermodr.Subscriptions package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Hermodr.Subscriptions'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true

      - name: Clean Hermodr.TestPublisher package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'Hermodr.TestPublisher'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true