name: Events PR Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/build-test.yml
    with:
      collect-coverage: false
      restrict-build-to-tfm: true
